### ISSUE TITLE
Misaligned pointer dereference

### ISSUE THREAD

**Issue by fgadaleta** [EmbarkStudios/physx-rs#210] opened 2023-08-29 08:07 UTC
**Describe the bug**

```
2023-08-29T08:14:34.620649Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
2023-08-29T08:14:34.621476Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-08-29T08:14:35.225130Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3060 Ti", vendor: 4318, device: 9353, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "525.125.06", backend: Vulkan }
thread 'main' panicked at /home/frag/.cargo/git/checkouts/bevy_mod_physx-ec641f3181f0becd/467a452/src/physx/src/traits/user_data.rs:26:41:
misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7ffff4a09606
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4e78abb437a0478d1f42115198ee45888e5330fd/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_nounwind_fmt
             at /rustc/4e78abb437a0478d1f42115198ee45888e5330fd/library/core/src/panicking.rs:106:14
   2: core::panicking::panic_misaligned_pointer_dereference
             at /rustc/4e78abb437a0478d1f42115198ee45888e5330fd/library/core/src/panicking.rs:193:5
   3: physx::traits::user_data::UserData::init_user_data
             at /home/frag/.cargo/git/checkouts/bevy_mod_physx-ec641f3181f0becd/467a452/src/physx/src/traits/user_data.rs:26:41
   4: physx::material::Material::from_raw
             at /home/frag/.cargo/git/checkouts/bevy_mod_physx-ec641f3181f0becd/467a452/src/physx/src/material.rs:122:25
   5: physx::physics::Physics::create_material
             at /home/frag/.cargo/git/checkouts/bevy_mod_physx-ec641f3181f0becd/467a452/src/physx/src/physics.rs:418:13
   6: <bevy_physx::PhysicsCore as bevy_app::plugin::Plugin>::finish
             at /home/frag/.cargo/git/checkouts/bevy_mod_physx-ec641f3181f0becd/467a452/src/lib.rs:334:22
   7: bevy_app::app::App::finish
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.0/src/app.rs:313:13
   8: bevy_winit::winit_runner::{{closure}}
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.11.0/src/lib.rs:352:17
   9: winit::platform_impl::platform::sticky_exit_callback
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:884:9
  10: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/mod.rs:334:17
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/mod.rs:443:31
  12: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/mod.rs:498:25
  13: winit::platform_impl::platform::EventLoop<T>::run
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:792:56
  14: winit::event_loop::EventLoop<T>::run
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/event_loop.rs:305:9
  15: bevy_winit::run
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.11.0/src/lib.rs:186:5
  16: bevy_winit::winit_runner
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.11.0/src/lib.rs:787:9
  17: core::ops::function::FnOnce::call_once
             at /rustc/4e78abb437a0478d1f42115198ee45888e5330fd/library/core/src/ops/function.rs:250:5
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/4e78abb437a0478d1f42115198ee45888e5330fd/library/core/src/ops/function.rs:250:5
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4e78abb437a0478d1f42115198ee45888e5330fd/library/alloc/src/boxed.rs:2007:9
  20: bevy_app::app::App::run
             at /home/frag/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.0/src/app.rs:292:9
  21: intrepid_sim::main
             at ./src/main.rs:129:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/4e78abb437a0478d1f42115198ee45888e5330fd/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
Aborted


```

**Comment by tgolsson** [comment] 2023-08-29 08:15
Please rerun with `RUST_BACKTRACE=1` so we can see the callstack.

**Comment by tgolsson** [comment] 2023-08-29 08:46
Thanks for the update! The misalignment here makes me wonder whether the passed in material itself is dead or owned by multiple. Is there a repository where I can run this code with a debugger attached?

@rlidwka CC :-)

**Comment by rlidwka** [comment] 2023-08-29 09:16
@tgolsson, can you maybe spot anything that can cause this error in the following `else` branch? UserData being stored here is empty tuple, `()`.

https://github.com/EmbarkStudios/physx-rs/blob/60827dd7af1d4c291cf257025aece72308ab8b69/physx/src/traits/user_data.rs#L26-L32

This is a spurious error. It failed at the first material being created, only on one machine, only with one example, only in debug mode, and it worked on the same machine before. I cannot reproduce it myself.

----

*The line it fails at is here:
https://github.com/rlidwka/bevy_mod_physx/blob/467a452eb94b069a6c997eadb0dcd13211e44673/src/lib.rs#L334*

*Be aware that that branch uses older physx-rs version that works with physx4 (because bindings for vehicles from physx5 don't exist yet), but relevant code in physx-rs hasn't changed since then.*

*If you want, you can run `cargo run --example vehicle` on the repository https://github.com/rlidwka/bevy_mod_physx, branch `physx4_20230717`, but I wouldn't expect it to do very much.*

**Comment by rlidwka** [comment] 2023-08-29 09:48
gonna debug it later today

**Comment by tgolsson** [comment] 2023-08-29 11:13
I'm really confused to be honest. Either the write is misaligned, or the read is... `()` has alignment of 1, but I don't think it could ever be aligned < 8 without breaking stack alignment in this code. Similarly, the write target is definitely offset by 16 from the start of the struct, which means that the PxMaterial would also be misaligned, which seems odd.

**Comment by tgolsson** [comment] 2023-08-29 11:15
Ok, as usual, the problem is apparent after refuting it. The read must be the problem. We're reading 8 bytes from a location containing 1 byte. And reading the 8 bytes enforces the 8-byte alignment. We should probably cast the *target* instead of the source... writing 1 byte to an 8-byte location is legal.

**Comment by rlidwka** [comment] 2023-08-29 13:35
> do you care to try switching the cast to the other side and seeing what falls out?

@tgolsson, on @fgadaleta's machine read seems to have alignment of 1 for the reasons I don't fully understand.

The following code works. Is this what you had in mind?

```rs
unsafe fn init_user_data(&mut self, user_data: Self::UserData) -> &mut Self {
    if size_of::<Self::UserData>() > size_of::<*mut c_void>() {
        // Too big to pack into a *mut c_void, kick it to the heap.
        let data = Box::into_raw(Box::new(user_data));
        *(self.user_data_ptr_mut() as *mut *mut c_void as *mut *mut Self::UserData) = data;
    } else {
        // DATA_SIZE <= VOID_SIZE
        *(self.user_data_ptr_mut() as *mut *mut c_void as *mut Self::UserData) = user_data;
    }
    self
}
```

**Comment by tgolsson** [comment] 2023-08-29 14:10
> @tgolsson, on @fgadaleta's machine read seems to have alignment of 1 for the reasons I don't fully understand.

You mean that the pointee has a 1-byte alignment? That's *correct* given that `()` has 1-byte alignment. I can't repro it actually having that alignment using `std::mem::align_of`-- when we take the address it would be spilled to stack and be 8-byte aligned as far as I can tell. But it might be debug vs release differences, architecture, etc.

> The following code works. Is this what you had in mind?
>
> ```rust
> <snip>
> ```

Yes, pretty much. The write-target is always going to be 8 bytes of space, aligned to 8 bytes on the heap, and the `userData` member is offset by 16 from that.

**Comment by fgadaleta** [comment] 2023-08-30 04:08
> > @tgolsson, on @fgadaleta's machine read seems to have alignment of 1 for the reasons I don't fully understand.
> 
> You mean that the pointee has a 1-byte alignment? That's _correct_ given that `()` has 1-byte alignment. I can't repro it actually having that alignment using `std::mem::align_of`-- when we take the address it would be spilled to stack and be 8-byte aligned as far as I can tell. But it might be debug vs release differences, architecture, etc.
> 
> > The following code works. Is this what you had in mind?
> > ```rust
> > <snip>
> > ```
> 
> Yes, pretty much. The userData is going to be aligned by 8-bytes inside its parent object in every situation, and always 8 bytes big.

Indeed in `release` there is no alignment problem.

**Comment by tgolsson** [comment] 2023-10-06 14:28
😕 Are you able to repro with the test too?

**Comment by rlidwka** [comment] 2023-10-07 11:03
> I am also confused now as to why this has never been a problem before.

Rust added these asserts in debug mode in Rust 1.70 (https://github.com/rust-lang/rust/pull/98112).

**Comment by tgolsson** [comment] 2023-10-07 16:32
There's a unit test here: https://github.com/EmbarkStudios/physx-rs/blob/1ef3b01b30add70c92870b7b86e7af049dd5d256/physx/src/traits/user_data.rs#L65-L113

**Comment by tgolsson** [comment] 2023-10-10 08:14
This looks like a different issue; cc @Jake-Shadle -- do you recognize it from rewriting the pxbind setup?

**Comment by tgolsson** [comment] 2023-10-10 13:50
I can repro the issue with flags, but we'll track that in the other issue. I can't repro the issue with `ball_physx`, and detect no issues with sanitizers. What platform/architecture are you using?

**Comment by tgolsson** [comment] 2023-10-11 09:02
Ah, ok. Closing again! I've wanted to make a release but haven't had the time. Will close this and try to do a release today.

**Closed by tgolsson** 2023-10-11 09:02 UTC
Labels: bug
